# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07f212047d36ef2763bd26d598b67f29a256e7b4068b6a1017a196eeb530f3828380005cdce1744e3e45ebb7a0e3d18637b7fd973df40929d2483eee5a350d14

test:
  secret_key_base: 3547662a2e317c6f414af56fbb5cba5f2205ac60a0d384e5121db12b1df749d45e112376f61ea814073ece8d7de3eef9f9c6898d2b34b5989981653837b43135

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
